project:
  type: website
  output-dir: ../docs
  lib-dir: site_libs
  render:
    - index.qmd
    - faq.qmd
    - computing/*.qmd
    - syllabus.qmd
    - schedule/index.qmd
    - schedule/slides/*.qmd

execute:
  freeze: auto

editor: source

repo-actions: false

website:
  title: UBC STAT 301
  repo-url: https://github.com/UBC-STAT/stat-301
  issue-url: https://github.com/UBC-STAT/stat-301/issues/new/
  repo-actions: [source, issue, edit]
  page-footer:
    background: primary
    center: "This work by Katie Burak and Gabriela V. Cohen Freue is licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0)<img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1'><img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1' /><img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1' />"

  navbar:
    pinned: true
    title: "{{< fa chart-column >}} UBC STAT 301"
    right:
      - text: Syllabus
        url: syllabus.qmd
      - text: Schedule
        url: schedule/index.qmd
     # - text: Worksheets
     #   url: https://github.com/UBC-STAT/stat-301
      - text: Computing
        url: computing/index.qmd
      # - text: Case Studies
      #   url: case-studies/index.qmd
      - text: FAQ
        url: faq.qmd
      - text: "{{< fa brands github >}} Github"
        url: https://github.com/UBC-STAT/stat-301
        
format:
  html:
    theme: [cosmo, assets/styles.scss]
    toc: true

