FROM prairielearn/grader-r:2ba3e7fcb3b38e102f1706ad61fb8f0e7fc15950

ADD install.R /

RUN Rscript --no-save install.R aer   binom   boot   car   cardata   caret   caret   cowplot \
   crayon   devtools   e1071   faraway   forecast  ggplot2 ggally   ggpubr  glmbb  glmnet   gridextra   \
   gridgraphics   gsdesign   hexbin   htmltools   htmlwidgets   infer   irkernel   islr  islr2  janitor   \
   kknn   latex2exp   leaps   mlbench   mltools   nycflights13   palmerpenguins  performance   plotly  qqplotr   \
   randomforest   rcurl   rmarkdown   rodbc   rpostgres   rsqlite   see   shiny  stringi  \
   testthat   tidymodels   tidyverse   titanic
