FROM prairielearn/grader-r:17dae10c6ffd1e8bce5ef7fe24b43228a4fee6b6

ADD install.R /

RUN Rscript --no-save install.R aer   base   binom   boot   car   cardata   caret   caret   cowplot \
   crayon   devtools   e1071   faraway   forecast   ggally   ggpubr  glmbb  glmnet   gridextra   \
   gridgraphics   gsdesign   hexbin   htmltools   htmlwidgets   infer   irkernel   islr  islr2  janitor   \
   kknn   latex2exp   leaps   mlbench   mltools   nycflights13   palmerpenguins  performance   plotly  qqplotr   \
   randomforest   rcurl   rmarkdown   rodbc   rpostgres   rsqlite   see   shiny  stringi  \
   testthat   tidymodels   tidyverse   titanic

