name: Publish r-stat-301-pl-workspace on DockerHub
on: 
  push: 
    paths: 
      - 'dockerfiles/r-stat-301-pl-workspace/Dockerfile'
      - 'dockerfiles/r-stat-301-pl-workspace/conda-linux-64.lock'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        ref: "main"

    - name: Create release tag
      id: release
      shell: bash
      run: echo "tag=$(git rev-parse --short=6 HEAD)" >> $GITHUB_OUTPUT

    - name: Build and publish STAT 301 pl workspace image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ubcdsci/r-stat-301-pl-workspace
        username: ${{ secrets.DOCKER_USERNAME_PERSONAL }}
        password: ${{ secrets.DOCKER_PASSWORD_PERSONAL }}
        workdir: "r-stat-301-pl-workspace"
        tags: "latest,${{ steps.release.outputs.tag }}"